### ISSUE TITLE
Missing README.md and LICENSE files

### ISSUE THREAD

**Issue by Slushee-a** [ribalta23/aleixribalta-portfolio#2]
# Issue
The license is unclear and there's no information about the project.

# Suggested fix
Add a LICENSE file (MIT, Apache, GPL, BSD...) and add a README.md file with details about the project and building/running instructions

**Comment by ribalta23** [comment]
Ready!! I have updated the repository by putting a README.md

**Comment by Slushee-a** [comment]
License file is still missing.
