### ISSUE TITLE
Social media icons clip through contact from

### ISSUE THREAD

**Issue by Slushee-a** [ribalta23/aleixribalta-portfolio#3]
# Issue
When viewing from a lower desktop, social media icons are rendered on top of the form submit button.

![image](https://user-images.githubusercontent.com/55996847/226176027-5bf2e002-8c17-4a0c-97c6-e031cf6ef672.png)

# Steps to reproduce
Open the website `https://aleixribalta.com/` from a low resolution desktop or a windowed browser 

# Browser information
| Browser         | Browser size  |
|--------------------|----------------------|
| Firefox 111.0 | 1336 x 651       |

**Comment by ribalta23** [comment]
And I have fixed the bug, I have made the web responsive.
